version: "3.8"

services:
  pg_db:
    restart: unless-stopped
    image: postgresql:15.2
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  # app:
  #   restart: always
  #   build:
  #     context: ./
  #     dockerfile: dockerfiles
  #   ports:
  #     - 8000:8000