FROM python:3.8-buster

ARG PYPI_SERVER_USER
ARG PYPI_SERVER_PASSWORD
ARG PYPI_SERVER_DOMAIN
ARG APP_VERSION
ENV PYPI_SERVER_URL https://${PYPI_SERVER_USER}:${PYPI_SERVER_PASSWORD}@${PYPI_SERVER_DOMAIN}/simple
EXPOSE 8000

RUN pip install -i ${PYPI_SERVER_URL} poc==${APP_VERSION}

ENTRYPOINT [ "run.sh" ]