name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        required: true

jobs:
  build:
    name: Build Packages (Python ${{ matrix.python-version }})
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set Build Version
        run: |
          echo ::set-env name=BUILD_VERSION::$(python setup.py --version)

      - name: Install dependencies
        run: |
          pip install twine wheel

      - name: Build Python Package
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/* -u ${{ secrets.PYPI_SERVER_USER }}  -p ${{ secrets.PYPI_SERVER_PASSWORD }} --repository-url ${{ secrets.PYPI_SERVER_URL }}

      - name: Build and push dockerfile
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}
          registry: docker.pkg.github.com
          repository: machineio/capuchino/poc
          tag_with_ref: true
          tags: ${{ env.BUILD_VERSION }}
          build_args: PYPI_SERVER_USER=${{secrets.PYPI_SERVER_USER}},PYPI_SERVER_PASSWORD=${{secrets.PYPI_SERVER_PASSWORD}},PYPI_SERVER_DOMAIN=${{secrets.PYPI_SERVER_DOMAIN}}
      - name: Kubernetes Deployment
