name: Styles

on: [push, pull_request]

jobs:
  lint:
    name: Lint Code (Python ${{ matrix.python-version }})
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Cache Dev Dependencies
      #   id: cache-dev-deps
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-py-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-py-${{ matrix.python-version }}-pip-
      #       ${{ runner.os }}-py-${{ matrix.python-version }}-
      #       ${{ runner.os }}-py-
      #       ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache-dev-deps.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements.txt
      - name: Run Linters
        run: |
          bash scripts/lint.sh
