name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Test Code (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      # - name: Cache Dev Dependencies
      #   id: cache-dev-deps
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-py-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-py-${{ matrix.python-version }}-pip-
      #       ${{ runner.os }}-py-${{ matrix.python-version }}-
      #       ${{ runner.os }}-py-
      #       ${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-dev-deps.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements.txt

      - name: Setup Upterm Session
        if: failure()
        uses: lhotari/action-upterm@v1

      - name: Run Pytest
        run: |
          bash scripts/test.sh --cov-report=xml --cov-fail-under=80
