name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Test Code (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    services:
      postgres:
        image: postgres:13.0-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: food
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Cache Deps
        uses: actions/cache@v2
        id: cache-dev-deps
        with:
          path: .venv
          key: venv-dev-${{ runner.os }}-py-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            venv-dev-${{ runner.os }}-py-${{ matrix.python-version }}
            venv-dev-${{ runner.os }}-py-
            venv-dev-${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-dev-deps.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run Pytest
        env:
          DB_DRIVER: postgresql
          DB_HOST: 0.0.0.0
          DB_PORT: 5432"
          DB_NAME: food
          DB_USER: root
          DB_PASSWORD: password
        run: |
          USE_LOCAL_DB_FOR_TEST=true 
          bash scripts/test.sh

      - name: Setup Upterm Session
        if: failure()
        uses: lhotari/action-upterm@v1
